### ISSUE TITLE
Question: How do I enable this? Running Guac in Docker

### ISSUE THREAD

**Issue by ilium007** [LagManCZ/guacamole-dark-theme#1]
I am running Guacamole in Docker using https://github.com/abesnier/docker-guacamole

Docker compose calls the two factor extension. Do I need to call this one as well? I assume the auth-totp is a Java class name?

```
services:
  guacamole:
    image: abesnier/guacamole:1.5.5-alpine-pg16
    container_name: guacamole
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
    environment:
      - EXTENSIONS=auth-totp
```
